version: "3.8"
services:
    mongodb:
      image: mongo
      container_name: mongodb
      env_file: .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      volumes:
        - mongodb-data:/data/db
      networks:
        - mongodb_network
      ports:
        - 27017:27017
      restart: unless-stopped

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        env_file: .env
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
          - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
          - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_ADMIN_USERNAME
          - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_ADMIN_PASSWORD
        volumes:
          - mongodb-data
        depends_on:
          - mongodb
        networks:
          - mongodb_network
        ports:
          - 8081:8081
        restart: unless-stopped

    HTTPserver:
      build:
        context: HTTPserver/
        dockerfile: Dockerfile
      image: rab-http
      container_name: rab-http
      restart: unless-stopped
      env_file: .env
      environment:
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_HOSTNAME=$MONGO_HOST
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
        - HTTP_PORT=$HTTP_PORT
      depends_on:
        - mongodb
      ports:
        - 3000:3000
      networks:
        - mongodb_network

    MatchmakingServer:
      build:
        context: MatchmakingServer/
        dockerfile: Dockerfile
      image: rab-matchmaking
      container_name: rab-matchmaking
      restart: unless-stopped
      env_file: .env
      environment:
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_HOSTNAME=$MONGO_HOST
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
        - MATCHMAKING_PORT=$MATCHMAKING_PORT
        - GAME_VERSION=$GAME_VERSION
      depends_on:
        - mongodb
      ports:
        - 8000:8000
      networks:
        - mongodb_network

volumes:
  mongodb-data:
     name: mongodb-data
networks:
  mongodb_network:
     name: mongodb_network
